<?php

namespace Bpstr\Components\Bootstrap\Behaviours;

abstract class ContextualAvareFamilyPrefixedComponent extends ContextualAvareComponent {

	public function render(): string {
		array_unshift($this->classes, sprintf('%s-%s', $this->family, $this->contextual));

		return parent::render(); // TODO: Change the autogenerated stub
	}

}
